### ISSUE TITLE
首次退出房间时触发的非法传输导致崩溃

### ISSUE THREAD

**Issue by ChrisWynyard** [project-redbud/FunGame-Server#9]
Milimoe.FunGame.SocketWrongInfoException: 收到错误的返回信息 (#10008)
   at Milimoe.FunGame.Core.Library.Common.Network.Socket.Receive() in C:\milimoe\FunGame.Core\Library\Common\Network\Socket.cs:line 71
   at Milimoe.FunGame.Desktop.Model.RunTimeModel.GetServerMessage() in C:\milimoe\FunGame.Desktop\FunGame.Desktop\Model\RunTimeModel.cs:line 212
   at Milimoe.FunGame.Desktop.Model.RunTimeModel.Receiving() in C:\milimoe\FunGame.Desktop\FunGame.Desktop\Model\RunTimeModel.cs:line 223
13:42:29 >> 无法连接至服务器，请检查你的网络连接。

**Comment by yeziuku** [comment]
> Newtonsoft.Json.JsonReaderException:“Additional text encountered after finished reading JSON content: {. Path '', line 42, position 1.”
> 
> JSON中包含两个JsonObject对象，因此他们不能转换为单一的SocketObject对象。因为服务器将QuitRoom的包和UpdateRoomMaster的包混在一起发送了，所以请检查服务器中对于QuitRoom的处理方法。
> 
> 有一种修复方式为：退出房间的玩家，不需要知道房主的变更信息。

其实有另一种方式，我们修改Core，循环解析JSON成多个SocketObject对象并广播即可。

**Comment by milimoe** [comment]
> > Newtonsoft.Json.JsonReaderException:“Additional text encountered after finished reading JSON content: {. Path '', line 42, position 1.”
> > 
> > JSON中包含两个JsonObject对象，因此他们不能转换为单一的SocketObject对象。因为服务器将QuitRoom的包和UpdateRoomMaster的包混在一起发送了，所以请检查服务器中对于QuitRoom的处理方法。
> > 
> > 有一种修复方式为：退出房间的玩家，不需要知道房主的变更信息。
> 
> 其实有另一种方式，我们修改Core，循环解析JSON成多个SocketObject对象并广播即可。

+1

**Comment by milimoe** [comment]
服务器显示为非法传输是因为QuitRoom返回了错误信息，QuitRoom的后续操作是UpdateRoom，应该是这个导致的。
